version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: vaex__s3_app
    volumes:
      - ./src:/src
      - ../Data:/data
      - ./tmp:/tmp
    environment:
      - "FILE_SIZE=${FILE_SIZE}"
    command: ["python", "main.py"]
    depends_on:
      - redis
      - celery
  redis:
    container_name: vaex__s3_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    container_name: vaex__s3_celery
    command: ['celery', '-A', 'scheduler.tasks', 'worker', '--loglevel=INFO']
    volumes:
      - ./src:/src
      - ./tmp:/tmp
    working_dir: /src
    depends_on:
      - redis
